services:

  template-server:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./.env
    volumes:
      - ".:/home/app"
    depends_on:
      - template-db
    ports:
      - "5050:5050"
    networks:
      - template-net

  template-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: template_db
    volumes:
      - db-data:/data/db
    networks:
      - template-net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret123@template-db:27017/template_db?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - template-db
    networks:
      - template-net

volumes:
  db-data:
    driver: local

networks:
  template-net:
    driver: bridge